apiVersion: v1
kind: Service
metadata:
  name: load-blance
  labels:
    name:  load-blance

spec:
  type: loadBalancer
  ports:
   - port: 8000
     targetPort: 8000
  
  selector:
    app: python-application
